### ISSUE TITLE
[Request] DPL set limit should be published (MQTT, Api,...)

### ISSUE THREAD

**Issue by DanielR92** [hoylabs/OpenDTU-OnBattery#1232]
### Is your feature request related to a problem? Please describe.

There is no problem. But publishing the limit would make a lot of sense here. So that other systems that are also connected via MQTT receive the current values. This also makes it possible to create logs and then understand more precisely how problems arise when they occur.

### Describe the solution you'd like

The relevant information for each inverter should be stored via MQTT.
powerlimiter -> status -> ID -> values
![grafik](https://github.com/user-attachments/assets/363a8eab-d6d2-4c7e-9585-04de473f2853)

### Describe alternatives you've considered

-

**Comment by spcqike** [comment]
if its of any help, you can use the limit reported by the inverter itself
![grafik](https://github.com/user-attachments/assets/62c5b077-d1ab-4d1d-a052-c98b62931a67)

but yes, maybe it would be smart to also publish the overall DPL limit, as we start to manage multiple inverters by the DPL at once. said limit would be the target production, wouldn't it?

**Comment by schlimmchen** [comment]
Oh, okay, to the current limit is indeed published already, makes sense.

However, the calculated household consumption, the effective (load-corrected) voltage, the expected AC output of each inverter, etc. should be published to MQTT. Essentially, I guess, these are the values that we are also missing in the non-existent DPL live view card.

**Comment by DanielR92** [comment]
Thanks @spcqike indeed I can use it already. Do you know how I can overly directly in HomeAssistant both graphics?

![grafik](https://github.com/user-attachments/assets/d6b16719-22cf-4a13-98b8-00ed8815cb0d)

**Comment by spcqike** [comment]
As I don’t use HA, no. No idea. 

I know how to do it with grafana and influx (:

**Comment by AndreasBoehm** [comment]
Has your issue been resolved @DanielR92 or do you think that it will be solved when the following issue has been implemented/resolved? https://github.com/hoylabs/OpenDTU-OnBattery/issues/1431

**Comment by schlimmchen** [comment]
@AndreasBoehm Good catch. Yes, this is obsoleted by #1431. And I assume that Daniel did indeed find the info he was interested in. I am going to close this issue. Daniel may re-open it if we missed something.
