### ISSUE TITLE
[Request] support for reading external temperature sensor DS18b20

### ISSUE THREAD

**Issue by pationair** [hoylabs/OpenDTU-OnBattery#1238]
### Is your feature request related to a problem? Please describe.

Hello, is it possible to connect an external sensor for temperature monitoring?

The easiest would probably be a DS18B20.

### Describe the solution you'd like

The idea would be to put this in the battery box to measure the temperature of the battery.

I would appreciate feedback.

### Describe alternatives you've considered

I am currently using an Aqara Zigbee sensor

**Comment by schlimmchen** [comment]
What BMS are you using and why does it not provide temperature data?

**Comment by pationair** [comment]
Hello, I have a Power Queen 25.6V 100Ah battery, it has a BMS, but as far as I know I can't read it.

**Comment by SW-Niko** [comment]
Hello @pationair ,
As an alternative solution you can maybe use the Victron "Smart Battery Shunt".
The Victron MPPT can use this information to stop charging the battery at low temperature and with PR #1292 you can see the temperature in the web UI.

**Comment by schlimmchen** [comment]
As I don't even support this if the code was contributed from someone else, I am going to close this as "not planned".
