### ISSUE TITLE
[Request] Proper RF Stats

### ISSUE THREAD

**Issue by schlimmchen** [hoylabs/OpenDTU-OnBattery#1246]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/bc1ad035-c418-4fa3-aca7-95dc12c17efd)

This is apparently part of AhoyDTU. I have thought of something like this before. This should definitely be part of OpenDTU (yes, the upstream project as well).

**Comment by stefan123t** [comment]
I think this has been implemented upstream and can be closed.
