### ISSUE TITLE
Firmware generic_esp32_8mb startet nicht (ESP32-DevKitC-VIE Board)

### ISSUE THREAD

**Issue by schlimmchen** [hoylabs/OpenDTU-OnBattery#1304]
Hallo @schlimmchen,

ich habe mir nun auch ein ESP32-DevKitC-VIE-Board (8MB Flash) wie Tiese zugelegt und habe heute das aktuellste Firmware-Release **2024.09.11** (**opendtu-onbattery-generic_esp32_8mb.factory.bin**) per USB-Kabel und mit dem Espressif "flash_download_tool_3.9.7" auf den ESP32 geflasht!

Hierbei ist mir aufgefallen, das ich nach dem Flashvorgang und dem Neustart vom ESP auch keine WLAN-Direktverbindung aufbauen kann.

Das selbe Problem besteht auch mit dem Firmware-Release **2024.08.18** (**opendtu-onbattery-generic_esp32_8mb.factory.bin**).
Hier kann ich nach dem Flashvorgang und dem Neustart vom ESP auch keine WLAN-Direktverbindung aufbauen,
wie Tiese das am 24.08. 2024 ursprünglich beschrieben hat:

> die neue Version 2024.08.18 läuft leider nicht mit dem ESP32-DevKitC-VIE-Board. 😕

> Dann habe ich den ESP32 komplett neu, mit dem Stand: development, geflasht: öffnet keine WLAN-Direktverbindung.

Nehme ich aber das Firmware-Release **2024.06.03** (**opendtu-onbattery-generic_esp32.factory.bin**) funktioniert die WLAN-Direktverbindung wieder und ich kann mich auf der Weboberfläche von OpenDTU-OnBattery anmelden!
Das hat Tiese am 24.08. 2024 auch so beschrieben:

> Alles wieder auf Version 2024.06.03 zurück: läuft wieder. 😀

Nun meine Frage:
Ist das noch ein Problem in der Firmware oder muss ich beim Flashvorgang zusätzlich etwas beachten?

Zur Info:
Alle 3 Firmware-Releases habe ich nach dem gleichen Schema per USB-Kabel und mit dem Espressif "flash_download_tool_3.9.7" auf den ESP32 geflasht!

_Originally posted by @the-lonely-one in https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/1028#discussioncomment-10802088_

**Comment by schlimmchen** [comment]
@the-lonely-one Bitte teile einen Link zu diesem Board. Was kommt denn auf der seriellen Konsole raus, nachdem du die Firmware programmiert hast? "Lebt" das Board?

Ich kann das Problem leider nicht reproduzieren um selbst mal zu schauen, da ich (noch) kein solches Board besitze.

**Comment by schlimmchen** [comment]
Sowas? https://www.digikey.de/de/products/detail/espressif-systems/ESP32-DEVKITC-VIE/12091811

Das hier wäre ohne Drama für mich bestellbar: https://www.conrad.de/de/p/espressif-esp32-devkitc-vie-entwicklungsboard-esp32-devkitc-vie-2490159.html Das ist jenes von dem wir reden, korrek?

**Comment by the-lonely-one** [comment]
> @the-lonely-one Bitte teile einen Link zu diesem Board. Was kommt denn auf der seriellen Konsole raus, nachdem du die Firmware programmiert hast? "Lebt" das Board?
> 
> Ich kann das Problem leider nicht reproduzieren um selbst mal zu schauen, da ich (noch) kein solches Board besitze.

Das ESP32-DevKitC-VIE-Board (8MB Flash) habe ich mir hier bestellt:
https://www.voelkner.de/products/5234207/Espressif-ESP32-DevKitC-VIE-Entwicklungsboard-ESP32-DevKitC-VIE.html?campaign_type=TXT&pla_campaign_no=9729477063&campaign_content=98311538583&campaign_term=&gad_source=1&gclid=EAIaIQobChMIs9bjt_LtiAMVRklBAh0oTjfzEAAYASAAEgLBVvD_BwE

Nachfolgend ein paar Infos, die evtl. hilfreich sein könnten:

Hier meine Einstellungen im Espressif "flash_download_tool_3.9.7":
![Screenshot 2024-10-01 210002](https://github.com/user-attachments/assets/c960b0e7-4d4d-4704-87b6-7c8e0da4d58f)

![Screenshot 2024-10-01 210341](https://github.com/user-attachments/assets/78f1ccd3-665e-4341-a432-7d93a1e9e641)

Ausgabefenster von Espressif "flash_download_tool_3.9.7" nachdem ich den ESP zuerst gelöscht und dann mit dem Firmware-Release **2024.09.11 (opendtu-onbattery-generic_esp32_8mb.factory.bin**) geflasht habe:
![Screenshot 2024-10-01 210426](https://github.com/user-attachments/assets/a54dcbfb-6a13-4ad6-bca4-ea7a04237df4)

Auszug aus der seriellen Konsole (USB-Verbindung) von PuTTY, nach dem ich den ESP geflasht habe:
![Screenshot 2024-10-01 210736](https://github.com/user-attachments/assets/995c0893-00e5-4aa8-91de-61062e2ea822)

**Comment by the-lonely-one** [comment]
> Sowas? https://www.digikey.de/de/products/detail/espressif-systems/ESP32-DEVKITC-VIE/12091811
> 
Richtig!

> Das hier wäre ohne Drama für mich bestellbar: https://www.conrad.de/de/p/espressif-esp32-devkitc-vie-entwicklungsboard-esp32-devkitc-vie-2490159.html Das ist jenes von dem wir reden, korrek?

Ja!

**Comment by schlimmchen** [comment]
Okay, alles klar, das hilft und das möchte ich ernst nehmen, der putty log sagt sehr deutlich, dass das flashen nicht geklappt hat oder das etwas mit der firmware nicht stimmt.

Kannst du versuchen, die firmware mal mit esptool.py zu flashen? Google hilft dir, das zu installieren...

Ich bestell mir mal so ein Board, kann aber frühestens Montagabend etwas dazu testen.

**Comment by the-lonely-one** [comment]
> Kannst du versuchen, die firmware mal mit esptool.py zu flashen? Google hilft dir, das zu installieren...

Nachdem ich mich heute mit Google etwas weitergebildet habe😀:

- Aktuelle "**python-3.12.7-amd64.exe**" heruntergeladen und beim mir auf dem Windows-PC installiert
- Das "**esptool.py**" via "**pip**" installiert
- Aktuelles Firmware-Release **2024.09.11 (opendtu-onbattery-generic_esp32_8mb.factory.bin)** mit dem Befehl:
"**esptool write_flash 0x0 ./opendtu-onbattery-generic_esp32_8mb.factory.bin**" geflasht!

Siehe hier:
![Screenshot 2024-10-06 142507](https://github.com/user-attachments/assets/547ecc00-98b2-43a3-b46f-303e94792a13)

Leider kann ich nach dem Neustart vom ESP weiterhin keine WLAN-Direktverbindung aufbauen kann.
Selbes verhalten, wie bisher!

Hier nochmal ein aktueller Auszug aus der seriellen Konsole (USB-Verbindung) von PuTTY, nach dem ich den ESP mit dem "**esptool.py**" geflasht habe:
![Screenshot 2024-10-06 142826](https://github.com/user-attachments/assets/78db7a9d-7255-41ed-bd42-d1d159991083)

Sieht eigentlich von der Ausgabe genau so aus, wie oben!

**Comment by schlimmchen** [comment]
Jup, das wird wohl heißen, dass die Firmware ein grundsätzliches Problem hat.

Mein ESP32 mit 8MB Flash ist unterwegs und ich schau mir das an, sobald der in meinen Händen ist.

**Comment by schlimmchen** [comment]
Erledigt mit f7605204. Danke an @Tiese, der in #1028 schon ausgetüftelt hat, was notwendig war.

@the-lonely-one Passende firmware findest du [im Build Run zum o.g. commit](https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/11242875907), in jedem weiteren Build des development Branches, sowie im nächsten Release.
