### ISSUE TITLE
DPL Mode change over http

### ISSUE THREAD

**Issue by Cartman586** [hoylabs/OpenDTU-OnBattery#1325]
### Describe the solution you'd like

I would like to send the dpl mode (1,2,3) via an http command 

### Additional context

I would like to send the dpl mode (1,2,3) via an http command. To do pic. Example: http://IP/dpl=0

**Comment by Cartman586** [comment]
> ### Is your feature request related to a problem? Please describe.
> _No response_
> 
> ### Describe the solution you'd like
> I would like to send the dpl mode (1,2,3) via an http command
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> I would like to send the dpl mode (1,2,3) via an http command

To do this see pic (inverter on/of via dpl)
![IMG_5504](https://github.com/user-attachments/assets/0764a9c2-211b-4da2-a4fa-394548e52b9e)

**Comment by AndreasBoehm** [comment]
Please take a look here why we won't provide a stable public HTTP for this and also the alternative that we offer: https://github.com/hoylabs/OpenDTU-OnBattery/issues/252#issuecomment-2051888923

You can check which API calls are made by the WebUI and replicate them within your setup but pleas be warned that this API is not stable and might change/break at any point.
