### ISSUE TITLE
(Full) Solar-Passthrough auf Basis von MQTT Daten über Victron2MQTT

### ISSUE THREAD

**Issue by iamdevnull** [hoylabs/OpenDTU-OnBattery#1328]
### Is your feature request related to a problem? Please describe.

Ich habe mithilfe von Victron2MQTT (https://all-solutions.store/de/shop/victron2mqtt-set/) die Daten des Ladereglers im HOAS MQTT Broker verfügbar.

Ich möchte gerne (Full) Solar-Passthrough nutzen, dies geht nicht aufgrund der harten Voraussetzung einer VE.Direct basierten physikalischen Anbindung zwischen DTU und Laderegler.

![image](https://github.com/user-attachments/assets/754df101-4dd1-4be3-965b-0d9f1faa0b9c)

### Describe the solution you'd like

Da die Daten des Ladereglers über MQTT verfügbar sind, könnten diese als Basis für den (Full) Solar-Passthrough Mode genutzt werden.

### Additional context

Dies ist nur eine Idee, wäre super, wenn dieser Ansatz geprüft werden könnte.

**Comment by schlimmchen** [comment]
Das ist ein Duplikat von #457. Wenn ich falsch liege mit dieser Einschätzung, melde ich bitte nochmal.
