### ISSUE TITLE
[Request] Solar-Charger Value via MQTT as Input to Power-Limiter

### ISSUE THREAD

**Issue by mkneppe** [hoylabs/OpenDTU-OnBattery#1411]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

The opendtu should be able to get the Power-supplied from Solar-Panels via MQTT or similar data-streams.
With this possiblity other data then from VE.Direct can be used.

**Comment by schlimmchen** [comment]
Duplicate of #457.
