### ISSUE TITLE
Meine openDTU On Battery aktualisiert sich nicht in der LIVE-ANSICHT (Browser)

### ISSUE THREAD

**Issue by KJ-202209** [hoylabs/OpenDTU-OnBattery#1420]
### What happened?

Die Live-Ansicht aktualisiert sich nur, wenn ich den Browser aktiv aktualisieren. 

### To Reproduce Bug

Die Anzeige im oberen Bereich friert ein.   ..... letzte Aktualisierung vor xx Sekunden

### Expected Behavior

Ich würde mich über einen Hinweis der Fehlerbehebung freuen; aber bitte Laien-verständlich. I

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU-OnBattery?

Systeminformationen Firmwareinformationen Hostname	OpenDTU-489B64 SDK-Version	v4.4.7-schmutzig Konfigurationsversion	0.1.28 Firmwareversion / git Hash	11.09.2024 Firmware-Zweig	Master PIO Umgebung	generic_esp32_4mb_no_ota Firmware-Aktualisierung	 Grund-CPU zurücksetzen 0	Vbat-Einschalt-Reset Grund CPU 1 zurücksetzen	für APP-CPU, Reset durch PRO-CPU Anzahl der Konfigurationsspeicherungen	45 Betriebszeit	0 Tage 01:17:35 Hardwareinformationen

### What firmware variant (PIO Environment)?

generic_esp32_4mb_no_ota

### Relevant log/trace output

```Shell
-
```

### Anything else?

Ich glaube so etwas schon gelesen zu haben 
@ #[schlimmchen](https://github.com/schlimmchen) hat ein Commit zu schlimmchen/OpenDTU-OnBattery hinzugefügt, das auf dieses Problem verweist [am 25. Februar](https://github.com/hoylabs/OpenDTU-OnBattery/issues/685#ref-commit-a1545f5)
@schlimmchen
[fix: copy OnBattery-specific data from live view websocket](https://github.com/schlimmchen/OpenDTU-OnBattery/commit/a1545f5b730135e9ff0e9c3ab5db61828ae81286) …
[a1545f5](https://github.com/schlimmchen/OpenDTU-OnBattery/commit/a1545f5b730135e9ff0e9c3ab5db61828ae81286)
[schlimmchen](https://github.com/schlimmchen) hat ein Commit zu schlimmchen/OpenDTU-OnBattery hinzugefügt, das auf dieses Problem verweist [am 25. Februar](https://github.com/hoylabs/OpenDTU-OnBattery/issues/685#ref-commit-fd320a1)
@schlimmchen
[fix: copy OnBattery-specific data from live view websocket](https://github.com/schlimmchen/OpenDTU-OnBattery/commit/fd320a136614c384abf712639d097bd5c7395eef) …
[fd320a1](https://github.com/schlimmchen/OpenDTU-OnBattery/commit/fd320a136614c384abf712639d097bd5c7395eef)
@[schlimmchen](https://github.com/schlimmchen) schlimmchen hat dieses Problem erwähnt [am 25. Februar](https://github.com/hoylabs/OpenDTU-OnBattery/issues/685#ref-pullrequest-2152731399)
https://github.com/hoylabs/OpenDTU-OnBattery/pull/696
Zusammengeführt

, ist aber für mich nicht ersichtlich was getan werden muss.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by schlimmchen** [comment]
Wie greifst du auf die OpenDTU-OnBattery WebApp zu? Ist da ein Reverse Proxy dazwischen?

Bitte mach, wenn es wieder möglich ist, einen Screenshot von Info -> System.

Glaubst du das aktuelle Release installiert zu haben?

**Comment by KJ-202209** [comment]
Zu 1. : ich gebe die Adresse (IP) 192.168.0.123 ein. Ganz normal über mein WLAN zu Hause.  Kein Proxy 
Zu 2.: anbei 
![Screenshot_20241125-210059](https://github.com/user-attachments/assets/9d50158f-bfc9-45d8-a189-ea176d1e4a11)
![Screenshot_20241125-210050](https://github.com/user-attachments/assets/16236925-2f35-46ec-842d-6da691a96eaf)
![Screenshot_20241125-210042](https://github.com/user-attachments/assets/6210606d-5f4f-4554-b87f-2455733e4ab9)
![Screenshot_20241125-210033](https://github.com/user-attachments/assets/6fed5a7b-97a2-48df-a434-2ad933ab10c6)

Zu 3.:  das weiß ich nicht, ich soll lt Verkäufer der dtu keine Update machen damit Tasmota richtig läuft.

**Comment by schlimmchen** [comment]
Sorry, aber es ist nicht in Ordnung dass du eine sonstwie modifizierte Version von OpenDTU-OnBattery einsetzt (die von deinem Verkäufer zusammengeschusterte) und hier im Originalprojekt ein Issue aufmachst.

Wende dich an den Verkäufer deiner Hardware. Wenn dessen Kram nur mit seiner Firmware funktioniert, dann muss er auch Unterstützung leisten.

**Comment by KJ-202209** [comment]
Auch von mir ein Sorry, ich dachte es wäre eine original Software
aufgespielt.. kann man die ersetzen??

Bernhard Kirchen ***@***.***> schrieb am Mo., 25. Nov. 2024,
21:15:

**Comment by schlimmchen** [comment]
Das kann ich dir leider nicht versprechen, das kommt auf die konkrete Hardware an. Starte doch mal eine Diskussion dazu und wir versuchen, dir zu helfen. Wo hast du das Teil gekauft? Gibt es das Angebot noch zwecks Nachlesen? Fotos von der Hardware. Beschreibung deiner Anforderungen (welche Wechselrichter, wie viele, Batterie ja/nein, wenn ja welche, welches Power Meter Interface, etc.). Die Herausforderung wird darin liegen, das Pin Mapping auf die Kette zu bringen, wenn der Lurchi, der dir das verkauft hat, das Mapping fest einkompiliert hat. Was erhälst du denn, wenn du die pin_mapping.json als Backup herunterlädst? Hast du eine Firmware-Datei vom Verkäufer erhalten, damit du die im Zweifel wieder einspielen kannst? Lass das in einer neuen Diskussion mal anschauen.

**Comment by KJ-202209** [comment]
Sorry, das verstehe ich alles nicht wirklich. Gekauft habe ich das Teil von
einer Firma. S.u mit dem Lesekopf zusammen.
Jürgen Reiser

Tremex Handelsgesellschaft mbH
Büro Dortmund
Tel.: 0231-9173421
Email : ***@***.***

Hauptsitz:

Innovationspark Wuhlheide
Köpenicker Straße 325 Haus 41
<https://www.google.com/maps/search/K%C3%B6penicker+Stra%C3%9Fe+325+Haus+41%C2%A0+%C2%A0%C2%A0%C2%A0+12555+Berlin?entry=gmail&source=g>

<https://www.google.com/maps/search/K%C3%B6penicker+Stra%C3%9Fe+325+Haus+41%C2%A0+%C2%A0%C2%A0%C2%A0+12555+Berlin?entry=gmail&source=g>
12555 Berlin
<https://www.google.com/maps/search/K%C3%B6penicker+Stra%C3%9Fe+325+Haus+41%C2%A0+%C2%A0%C2%A0%C2%A0+12555+Berlin?entry=gmail&source=g>

Tel.: 030-65762630
mail : ***@***.***
web : tremex.de
HRB130661 Amtsgericht Charlottenburg
GF Folker Stange
Us-Id.-Nr: DE275575667


Antworten
<https://www.ebay.de/ulk/messages/reply?M2MContact&item=285979490081&requested=tremex-gmbh&qid=3040377878018&redirect=0&self=k.janosch&mkevt=1&mkpid=0&emsid=e12052.m44.l1139&mkcid=7&ch=osgood&euid=0400052993cb4841b259bd41f31cf868&bu=44182530041&osub=-1%7E1&crd=20240828002038&segname=12052>
Artikel ansehen
<https://www.ebay.de/itm/285979490081?mkevt=1&mkpid=0&emsid=e12052.m44.l1123&mkcid=7&ch=osgood&euid=0400052993cb4841b259bd41f31cf868&bu=44182530041&osub=-1%7E1&crd=20240828002038&segname=12052>

Bernhard Kirchen ***@***.***> schrieb am Mo., 25. Nov. 2024,
21:32:

**Comment by stefan123t** [comment]
@KJ-202209 unter System > Config kannst Du ein Backup der config.json und der pin_mapping.json machen.
Bei Dir ist die Version 11.09.2024 installiert. Ich nehme an das sollte 2024.09.11 entsprechen. Ich glaube damals gab es einige Schwierigkeiten mit dem ESPAsyncWebServer Modul bzw es wurde danach auf eine aktuellere Version geändert.
Daher vermute ich mal Deine Probleme könnten mit einer aktuelleren Firmware gelöst werden.
Wie schlimmchen schon schrieb musst Du dafür vorher ein Backup Deiner pin_mapping.json hier teilen und ein Backup der config.json (WLAN Passwort, etc) für alle Fälle aufbewahren.
Um notfalls wieder die Firmware Deines Herstellers einspielen zu können solltest Du auch davon ein Firmware Image / Kopie haben. Die kann Die aber evtl. nur Dein Händler geben.

**Comment by KJ-202209** [comment]
Vielen Dank für die Antwort. Ich habe keine Installationsdatei bekommen.
Ich kann versuchen die über den Anbieter zu bekommen und dann wie
beschrieben vorgehen. Vorausgesetzt ich bekomme das hin.
Ist es eventuell ein Upgrade meiner alten openDTU auf die openDTU OnBattery
einfacher?? Von der habe ich auch die Installationsdatei.
VG Konstantin

stefan123t ***@***.***> schrieb am Di., 26. Nov. 2024, 02:09:

**Comment by stefan123t** [comment]
@KJ-202209 Du hast mE. eine DX-DTU des Herstellers Diamex: 

[DX-DTU Bundle für Nulleinspeisung Hoymiles HM-DTU mit OpenDTU + IR-Lesekopf](https://www.ebay.de/itm/285979490081)

Wir kennen die genauen Details dieser “closed source” Hardware nicht. Bitte besprich alles weitere mit Deinem Händler oder Hersteller.
Weder wir noch das Upstream Projekt OpenDTU können / wollen für diesen kommerziellen Hersteller Support leisten.

Ich glaube es gab dazu bereits Diskussionen im Discord und vielleicht findest Du die Pin Belegung für die pin_mapping.json auf dem Beipackzettel.
Die Installation sollte prinzipiell genauso wie für andere Boards funktionieren aber genau wissen wir es nicht.

Ebenso weiß ich nicht ob die Hardware DX-DTU überhaupt für OpenDTU-OnBattery geeignet ist. Ich meine die Hardware Anforderungen sind in letzter Zeit aufgrund des zunehmenden Funktionsumfangs gestiegen. D.h. man muss u.U. per USB Kabel flashen und kann nicht mehr OTA per WebGUI flashen!

@schlimmchen ich glaube das issue kannst Du hiermit schliessen und der Nutzer kann sein Problem anderweitig klären.

**Comment by KJ-202209** [comment]
Vielen Dank, ich werde es mal versuchen.
Wie schon gesagt habe ich noch eine alte dtu, nicht von Tremex. Vielleicht
geht da zur Not ein Upgrade.
Darf ich mich melden, falls ich noch irgendwas nicht verstehe???

stefan123t ***@***.***> schrieb am Di., 26. Nov. 2024, 12:28:

**Comment by stefan123t** [comment]
@KJ-202209 wie von schlimmchen geschrieben bitte nicht hier im Issue Deine persönlichen Installations / Flash Probleme diskutieren, sondern entweder über die Discussion Funktion im github oder vermutlich besser noch im Discord Chat.

Für die Diamex / Tremex DX-DTU bitte ausschließlich mit dem Hersteller kommunizieren, weil wir dazu keine Details kennen.

**Comment by KJ-202209** [comment]
Okay

stefan123t ***@***.***> schrieb am Di., 26. Nov. 2024, 13:19:
