### ISSUE TITLE
[Bug] Huawei R4850G2 temperature values incorrect when actually lower than 0°C

### ISSUE THREAD

**Issue by Solarteur** [hoylabs/OpenDTU-OnBattery#1432]
### What happened?

Yesterday it was quite cold in the garage, the initial temperature on the Huawei R4850G2 was initially displayed as **4194303 °C**, then after a few minutes of operation it showed **1 °C**, which is closer to reality.
![Huawei_Temperaturen](https://github.com/user-attachments/assets/830f502a-6cf1-4a7a-94a8-b9dd7aad74d6)

### To Reproduce Bug

Operating the Huawei R4850G2 at low temperatures. I only have this device and therefore cannot rule out that the error comes from Huawei.

According to the specification, the "operating temperature range" is -40 °C - +75°C.

### Expected Behavior

Display also of sub-zero temperatures.

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU-OnBattery?

2024.11.20

### What firmware variant (PIO Environment)?

generic_esp32_4mb_no_ota

### Anything else?

For the sake of completeness, no priority.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by schlimmchen** [comment]
@Solarteur Unfortunately, I still don't have such an AC charger (maybe I will gift one to myself this christmas :wink:), so I need you to please test the [firmware built in the context of PR#1433](https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12115922101?pr=1433). Can you do that?

**Comment by Solarteur** [comment]
Sure, I'll do this test. Since it's warmer now, I won't be able to say anything about the results until the temperatures drop.

**Comment by Solarteur** [comment]
With PR#1433, temperatures below 0 °C are also displayed correctly - thank you!

![Huawei_Temperaturen_Patch](https://github.com/user-attachments/assets/494e9e8f-6686-408f-bafc-8631b9d21912)

**Comment by schlimmchen** [comment]
Awesome! Thanks for testing!
