### ISSUE TITLE
DPL mode changes automatically (2>0)

### ISSUE THREAD

**Issue by Cartman586** [hoylabs/OpenDTU-OnBattery#1437]
### What happened?

I use the Home Assistant to change and control the DPL mode. 
It is a HMS-2000
![1](https://github.com/user-attachments/assets/af046c7f-42a6-45c1-80fd-e3e6a85f9d6a)
![2](https://github.com/user-attachments/assets/10f8d455-dcd6-42da-9109-35639cb9eb47)

DPL Mode 0 = Feed ON (0% feed)
DPL Mode 2 = Feed OFF

Since recently, the openDTU has probably changed the value automatically, here for example at 22:46 and I don't know why.

I would be glad about help

### To Reproduce Bug

-

### Expected Behavior

- 

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU-OnBattery?

2024.11.20

### What firmware variant (PIO Environment)?

generic_esp32s3_usb

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by Cartman586** [comment]
@schlimmchen kannst du hier helfen?

**Comment by schlimmchen** [comment]
Was ist denn die Uptime deiner DTU? Startet die vielleicht neu? Wenn nicht sehe ich keinen anderen Grund, außer das halt etwas in deinem Netzwerk das Topic entsprechend schreibt.

**Comment by Cartman586** [comment]
@schlimmchen : Danke für den Hinweis. ja es steht drin vor ca. 16 Stunden neu gestartet. Ohne mein Eingreifen das würde zeitlich passen. Wie kann ich den Neustart unterbinden? Das war vor einiger Zeit nicht so

**Comment by schlimmchen** [comment]
Schließ einen Rechner an per USB und logge den Neustart das nächste mal mit, teile das Log, und dann kann jemand es dir vielleicht sagen.

Oder beobachte/plotte wenigstens den freien Heap und die anderen systemdaten um wenigstens ne indikation zu finden, woran es liegen könnte.

Lass keine Browserfenster zur DTU offen, jedenfalls nicht mit Konsolenausgaben.

Ansonsten ist das natürlich schade dass deine DTU neuerdings unverhofft neu startet, aber "das war vorher nicht so"... ganz ehrlich, dann mach halt nen downgrade. Regressionen sind Teil des Fortschritts, is halt so.

**Comment by stefan123t** [comment]
Ich nehme an um 22:46:44 hat der WR mit der Einspeisung begonnen.
Um 05:47:28 hast Du den WR über ein Remote Command abgeschaltet, danach ist er aus.

Wo ist das Problem ?

Die Reihenfolge der Events im Event Log ist ja immer schon ein bisschen wirr, speziell bei vormittags / nachmittags Events bzw. Start/Stop Wechseln. Da das Event Log nur 12 Stunden Werte und ein /zwei zusätzliche(s) am/pm Bits/Flags kennt.

@schlimmchen Ich glaube bei Ahoy werden die Events in der Zwischenzeit nach der Uhrzeit sortiert ausgegeben, aber das kann bei einem OpenDTU-OnBattery Inverter auch leicht schief gehen, da dieser ja auch die Nacht über an ist und dann evtl die jüngeren Morgenstunden erst nach den Abendstuden kommen ?

**Comment by Cartman586** [comment]
@schlimmchen , @stefan123t Es geht nochmals darum, dass ich mit HomeAssistant arbeite. Sende ich über MQTT den Befehl DPL Mode 2, dann wird das Einspeisen über den Dynamic Power Limiter der openDTUonBattery gestoppt. Wenn ich wieder mit der 0% Einspeisung weiter machen möchte, dann sende ich den Befehl DPL Mode 1 und der Dynamic Power Limiter der openDTUonBattery arbeitet wieder weiter und speist wieder bedarfsgerecht ein.

Da ja jetzt die openDTU immer wieder von selbst (ich kenn den Grund nicht) von selber startet, setzt er hier den Befehl nach dem Neustart automatisch auf DPL Mode 1 und speist ein, obwohl ich das zu diesem Zeitpunkt überhaupt nicht möchte.

Ich bin jetzt wieder auf die openDTUonBattery Version 2024.10.22 und habe hier das Problem nicht mehr. Das tritt erst seit der Version 2024.11.22 auf und ist für mich ein Fehler. Zumindest sollte man hier einbauen, neustart der openDTUonBattery nicht zulassen.

**Comment by stefan123t** [comment]
@Cartman586 ohne USB Serial Logfiles des Reboot Problems können wir Dir nicht weiterhelfen.
Damit ist zwar zumindest bewiesen, dass es ohne Reboot in der alten Version geht, aber halt nicht warum der Reboot in der aktuellen/ neueren Version auftritt.

**Comment by Cartman586** [comment]
Das Problem lässt sich problemlos nachstellen, auch ohne den Befehl. Meine zweite DTU die nicht gesteuert wird startet auch neu. Schaut mal bei euren DTUs, ob die selber neustarten, seht ihr ja an der Zeit, dass die nicht mehr mehrere Tage durchlaufen

**Comment by spcqike** [comment]
@Cartman586 unabhängig vom Neustart der DTU, solltest du dein DPL Mode Problem in HA abfangen und anderweitig lösen.

Wenn du die 2 willst, warum auch immer aber die 0 gesetzt wird (durch Neustart, Stromausfall, ... oder weil du in der Config was geändert hast), dann musst du die 2 eben zeitnah neu setzen. 

Ich hab sowas ähnliches in Node Red umgesetzt. ich frage aller 5 Minuten den zu erwartetenden Tagesertrag ab und setze, je nach Ertrag, den DPL auf 0 oder 2, aber eben nur, wenn er nicht bereits "korrekt" gesetzt ist. Dafür vergleiche ich halt mein berechnetes Soll mit dem zuletzt von der DTU gemeldeten Ist.

Schneller wäre so eine Korrektur noch, wenn ich mein Soll als Flag zwischenspeichere und auf ein update des Ists prüfe, ob noch immer Soll=Ist. und ggf. wieder ein Update schicke.

**Comment by Cartman586** [comment]
Für mich leider keine Lösung. Ich möchte schlicht das er im Normalbetrieb nicht neu startet
