### ISSUE TITLE
[Request] Disable power limit scaling if inverter has "new" Firmware

### ISSUE THREAD

**Issue by schlimmchen** [hoylabs/OpenDTU-OnBattery#1472]
### Is your feature request related to a problem? Please describe.

See #1445.

### Describe the solution you'd like

When executing the function to scale the inverter's power limit because the respective setting is enabled, we shall test if the inverter has "the new firmware" (whatever that exactly is for the particular model?!) installed and prevent scaling the power limit in that case. Print a big fat warning text in the log (non-verbose) if so. Edit the tooltip in the DPL UI to indicate that the setting shall be disabled for inverters running "the new firmware". If possible, hide the setting if the inverter firmware is known and indicates that overscaling is counter-productive. Implement a function to tell this, which can be used in the overscaling function as well in the web API that prepares the inverter meta data for the DPL UI.

**Comment by spcqike** [comment]
Frage meinerseits:
Gab es nicht vor der „überskalierung“ bereits eine „normale“ Skalierung? Ursprünglich für den Fall, dass man konkret nur x von y Eingängen überhaupt belegt hat? Bspw einen bei nem hm-800 um nur bis zu 400W einzuspeisen? 
Und, greift die normale Skalierung, so sie denn noch existiert, immer noch?

**Comment by AndreasBoehm** [comment]
Ja diese Skalierung gibt es. Die sollten wir auch loswerden.

**Comment by AndreasBoehm** [comment]
Ich kauf mir jetzt ne original DTU um das Update testen zu können.

**Comment by schlimmchen** [comment]
Achso, Mist... Na das ist dann ein Problem, wenn man die nicht ausschalten kann und die neue FW hat. Aber nur, wenn tatsächlich Eingänge nicht angestöpselt sind.

**Comment by AndreasBoehm** [comment]
Die Skalierung macht natürlich auch Probleme wenn jemand einen Akku zwischenschaltet der nur an zwei Anschlüssen hängt. B2500 und co.

**Comment by Exodusnick** [comment]
Super vielen Dank @schlimmchen 👍

**Comment by schlimmchen** [comment]
Wofür? Andreas hat es umgesetzt :wink: Der freut sich, dass du dankbar bist. Wir beide tun es :blush:

**Comment by Exodusnick** [comment]
Danke auch an dich @AndreasBoehm .

**Comment by schlimmchen** [comment]
Ja, genau, danke fürs Mitdenken!
