### ISSUE TITLE
is there a chance to include a second akku ? via mqtt

### ISSUE THREAD

**Issue by mikewolf99** [hoylabs/OpenDTU-OnBattery#1490]
### Is your feature request related to a problem? Please describe.

is there a chance to include a second akku ? via mqtt

### Describe the solution you'd like

**is there a chance to include a second akku ? via mqtt**

### Describe alternatives you've considered

is there a chance to include a second akku ? via mqtt

**Comment by AndreasBoehm** [comment]
This is not possible and would require a lot of work.

I would suggest to somehow combine the data of both in a meaningfull way, if even possible, in nodered or homeassistant and provide the combined data via mqtt.

**Comment by mikewolf99** [comment]
thanks for the answer
